# Generated by Django 2.2.17 on 2021-01-21 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
